export const FormFields = {
  CARD_NUMBER: 'CARD_NUMBER',
  CARD_HOLDER: 'CARD_HOLDER',
  EXPIRATION_DATE_MONTH: 'EXPIRATION_DATE_MONTH',
  EXPIRATION_DATE_YEAR: 'EXPIRATION_DATE_YEAR',
  CVV: 'CVV',
}
